import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by build process
precacheAndRoute(self.__WB_MANIFEST || []);

// Service Worker für DFWA
// Wird durch vite-plugin-pwa automatisch erweitert und verwaltet
// Diese Datei definiert Custom Runtime Caching Strategien

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Fallback für offline Navigation
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  
  // API-Anfragen: Network-First mit 3s Timeout
  if (url.pathname.startsWith('/api/')) {
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          if (response && response.status === 200) {
            const responseClone = response.clone();
            caches.open('api-cache').then((cache) => {
              cache.put(event.request, responseClone);
            });
          }
          return response;
        })
        .catch(() => {
          return caches.match(event.request).then((cachedResponse) => {
            return cachedResponse || new Response('Offline - API not available', { status: 503 });
          });
        })
    );
    return;
  }

  // Statische Assets: Cache-First
  if (
    /\.(js|css|woff2?|ttf|eot|png|jpg|jpeg|svg|webp|ico)$/i.test(url.pathname) ||
    url.pathname.includes('/assets/')
  ) {
    event.respondWith(
      caches.match(event.request).then((cachedResponse) => {
        return cachedResponse || fetch(event.request);
      })
    );
    return;
  }

  // Navigation: Network-First mit Cache Fallback
  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          if (response && response.status === 200) {
            return response;
          }
          return caches.match('./index.html');
        })
        .catch(() => {
          return caches.match('./index.html');
        })
    );
  }
});
