import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by build process
precacheAndRoute(self.__WB_MANIFEST || []);

const CACHE_NAMES = {
  STATIC: 'static-v1',
  API: 'api-v1',
  NAV: 'nav-v1',
};

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('install', (event) => {
  event.waitUntil(self.skipWaiting());
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.map((key) => {
          if (!Object.values(CACHE_NAMES).includes(key)) {
            return caches.delete(key);
          }
        })
      );
    })
  );
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // API-Anfragen: Stale-While-Revalidate für Leaderboard & Analytics
  if (url.pathname.startsWith('/api/')) {
    // Nur GET-Requests cachen
    if (event.request.method !== 'GET') return;

    event.respondWith(
      caches.open(CACHE_NAMES.API).then((cache) => {
        return cache.match(event.request).then((cachedResponse) => {
          const fetchPromise = fetch(event.request).then((networkResponse) => {
            if (networkResponse && networkResponse.status === 200) {
              cache.put(event.request, networkResponse.clone());
            }
            return networkResponse;
          });
          return cachedResponse || fetchPromise;
        });
      })
    );
    return;
  }

  // Statische Assets: Cache-First mit Network-Fallback & Update
  if (
    /\.(js|css|woff2?|ttf|eot|png|jpg|jpeg|svg|webp|ico)$/i.test(url.pathname) ||
    url.pathname.includes('/assets/')
  ) {
    event.respondWith(
      caches.match(event.request).then((cachedResponse) => {
        if (cachedResponse) return cachedResponse;
        return fetch(event.request).then((networkResponse) => {
          if (networkResponse && networkResponse.status === 200) {
            const cacheClone = networkResponse.clone();
            caches.open(CACHE_NAMES.STATIC).then((cache) => cache.put(event.request, cacheClone));
          }
          return networkResponse;
        });
      })
    );
    return;
  }

  // Navigation: Network-First mit Cache Fallback
  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          if (response && response.status === 200) {
            const cacheClone = response.clone();
            caches.open(CACHE_NAMES.NAV).then((cache) => cache.put(event.request, cacheClone));
            return response;
          }
          return caches.match('./index.html');
        })
        .catch(() => {
          return caches.match('./index.html') || caches.match(event.request);
        })
    );
  }
});
